### ISSUE TITLE
No override of ATC

### ISSUE THREAD

**Issue by vanosten** [hardba11/bourrasque#64] opened 2018-06-17 08:59 UTC
Hi

It seems to me that even though I have voice ATC disabled in FG, when approaching e.g. PHNL and being in APP mode the ATC voice is automatically enabled. I might be wrong about this, but I would rather not have it enabled - or have a choice to do so.

Btw: is there a way to get into APP mode but only see carrier stuff (TACAN) on the HUD instead of airport? e.g. using the Truman demo I automatically get approach info of PHNL on the HUD, but I actually am in range of a carrier and would like to have guidance on the carrier instea.

**Comment by hardba11** [comment] 2018-07-12 09:52
hi,

for the first issue, I can't reproduce it, what is your version of FG and what is your OS ?

For the tacan, the idea is good, I will add a new functionnality soon.

**Comment by hardba11** [comment] 2018-07-31 12:03
- can't reproduce first issue
- tacan : DONE (issue #65 )

so I close this issue #64

**Closed by hardba11** 2018-07-31 12:03 UTC
